version: 0.2

phases:
  install:
    commands:
      - echo "Installing Rust"
      - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal --default-toolchain stable
      - . "$HOME/.cargo/env"
      - rustup --version
      - echo "Installing Cargo Lambda + Zig"
      - make cargo-lambda
      - . $HOME/.bashrc
  pre_build:
    commands:
      - echo "Configure credentials profile"
      - mkdir ~/.aws/ && touch ~/.aws/credentials
      - echo "[transcribe-lambda-dev]" > ~/.aws/credentials
      - echo "aws_access_key_id=$ACCESS_KEY" >> ~/.aws/credentials
      - echo "aws_secret_access_key=$SECRET_KEY" >> ~/.aws/credentials
      - ENV=prod make ecr-login
  build:
    commands:
      - echo "Build & Deploy Listener"
      - cd lambda-fxns/listener
      - ENV=prod make deploy-zip
      - echo "Build & Deploy Cleanup"
      - cd ../cleanup
      - ENV=prod make deploy-zip
      - echo "Build & Deploy Transcriber"
      - cd ../transcriber
      - chmod 755 transcribe.sh
      - ENV=prod make image
      - ENV=prod make ecr-push
      - ENV=prod make update-lambda-code
#      - sleep 120 # wait 2 min to ensure change
#      - ENV=prod make update-lambda-config